default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 32

test:
  adapter: sqlite3
  database: db/test.sqlite3

development:
  adapter: sqlite3
  database: db/development.sqlite3

sandbox:
  <<: *default
  username: root
  password: dlqlwkfhrksek!!
  host: localhost
  database: ibiza_sandbox

production:
  <<: *default
  username: root
  password: dlqlwkfhrksek!!
  host: localhost
  database: ibiza_production
