# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5788009ed7d6fa5064f28e194f25868e9707eaeb5751df1fafbc46357ec86b02f9982a9768d4c8573e322e18699812de581404192662c6e7bc3a8e24cb1d06d6

test:
  secret_key_base: f277774214f879dce480d262d43febaf2dcfbd3fd456301695ec180a785349c7c76bad90836a073d407baa839f6fba0764722496809b1ed3faa27e1c876fb8b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
